<a href="https://colab.research.google.com/github/JCF-the-creator/GoogleColabGeneration/blob/main/Aula6_Armazenamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

dados = {
    'nome':['André','Paulo','Aline','Paola'],
    'idade':[36,25,30,18],
    'cidade':['Soracaba','Indaiatuba','São Paulo','Registro']
}

df_dados = pd.DataFrame(dados) #aqui declaramos uma variavel para o dataFrame, como norma utilizamos df_ para informar o dataFrame

display(df_dados)

    nome  idade      cidade
0  André     36    Soracaba
1  Paulo     25  Indaiatuba
2  Aline     30   São Paulo
3  Paola     18    Registro

In [4]:
df_dados.to_csv("teste_dados.csv", index=False) #cria o arquivo, no google Colab utiliza o path /content

df_ler_dados = pd.read_csv("/content/teste_dados.csv")

#temor técnico para adicionar informações numa tabela é "popular"

novos_dados = {
    'nome': ['Flávia', 'Cláudio', 'Fernanda'],
    'idade': [50, 63, 32],
    'cidade': ['Sorocaba', 'Iguape', 'Curitiba']
}

df_novos_dados = pd.DataFrame(novos_dados)

# usa a função pd.concat para 'juntar' os dados
# ignore_indez é para não deixar o index antigo da tabela, gerando um novo index
#dentre os itens da lista de df ele sempre vai mostrar as tabelas na ordem da lista
df_dados_juntos = pd.concat([df_ler_dados, df_novos_dados], ignore_index=True)

    nome  idade      cidade
0  André     36    Soracaba
1  Paulo     25  Indaiatuba
2  Aline     30   São Paulo
3  Paola     18    Registro